---
- name: Update and upgrade apt packages
  apt:
    autoclean: yes
    autoremove: yes
    upgrade: full
    update_cache: yes
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required  
  notify: reboot server
